apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-argocd-app
  namespace: todo
spec:
  project: default
  source:
    repoURL: https://github.com/lhtran-todo/kubernetes-yaml.git
    targetRevision: HEAD
    path: ./app
  destination:
    server: https://kubernetes.default.svc
    namespace: todo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true