apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-argocd-app
  namespace: todo
spec:
  project: default
  source:
    repoURL: https://github.com/lhtran-todo/kubernetes-yaml.git
    targetRevision: dev
    path: todo-chart
    helm:
      releaseName: todo
      valueFiles:
        - "./dev-local-values.yaml"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: todo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true     